# Generated by Django 4.1.1 on 2023-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_eventbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventbooking",
            name="date",
            field=models.DateField(verbose_name="%M:%H:%Y"),
        ),
    ]
