# Generated by Django 4.1.1 on 2023-06-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_usereventbooking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usereventbooking", old_name="user", new_name="user_name",
        ),
    ]
